export const COLORS = {

  TEXT_PRIMARY: '#1A1A1A',
  TEXT_SECONDARY: '#666666',
  TEXT_TERTIARY: '#999999',
  TEXT_DISABLED: '#CCCCCC',
  TEXT_INVERSE: '#FFFFFF',

  BG_PRIMARY: '#F5F7FA',
  BG_CARD: '#FFFFFF',
  BG_SURFACE: '#F9F9F9',

  RED: '#FF3B30',

  BORDER: '#E5E5E5',
  SHADOW: '#000',
  ACCENT_YELLOW: '#ffd500'
};